config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render 'edit'
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit class: "btn btn-outline-primary mt-3"%>
<% end %>

app/views/flats/create.html.erb
<h1>Flats#create</h1>
<p>Find me in app/views/flats/create.html.erb</p>

app/views/flats/delete.html.erb
<h1>Flats#delete</h1>
<p>Find me in app/views/flats/delete.html.erb</p>

app/views/flats/edit.html.erb
<div class="container">
  <div class="row">
    <%= render 'form', flat: @flat %>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="m-5">All our flats ( <%= @flats.count %> ) </h2>
  </div>
  <div class="row">
      <% @flats.each do |flat| %>
      <div class="col-4 mb-3">
        <div class="card-deck d-flex justify-content-around">
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= flat.name %></h5>
              <p class="card-text"><%= flat.address %></p>
              <p><i class="fas fa-users"></i><%= flat.number_of_guests %>
              <i class="fas fa-euro-sign"></i><%= flat.price_per_night %></p>
            </div>
            <div class="card-footer">
              <small class="text-muted"><%= link_to "More Info", flat_path(flat)  %></small>
              <small class="text-muted"><%= link_to "Edit", edit_flat_path(flat), class: "text-warning"  %></small>
              <small class="text-muted"><%= link_to "Remove", flat_path(flat), class: "text-danger", method: "delete" %></small>
            </div>
          </div>
        </div>
       </div>
       <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row">
    <%= render 'form', flat: @flat %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="banner" style="background-image: url(https://raw.githubusercontent.com/lewagon/layouts-demo/gh-pages/images/mapbox.png); height: 320px; background-size: cover;">
</div>
<div class="container">
  <div class="row">
    <div class="col-7">
      <div class="card bg-light mt-3 mb-2">
        <div class="card-body">
        <h5 class="card-title"><%= @flat.name %></h5>
        <p class="card-text"><%= @flat.address %></p>
      </div>
    </div>
    <div class="col-4">
      <div>
        <form>
        <div class="form-group">
          <label for="exampleFormControlInput1">Email address</label>
          <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
        </div>
        <div class="form-group">
          <label for="exampleFormControlSelect1">Example select</label>
          <select class="form-control" id="exampleFormControlSelect1">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
          </select>
        </div>
        <div class="form-group">
          <label for="exampleFormControlSelect2">Example multiple select</label>
          <select multiple class="form-control" id="exampleFormControlSelect2">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
          </select>
        </div>
        <div class="form-group">
          <label for="exampleFormControlTextarea1">Example textarea</label>
          <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
        </form>
      </div>
    </div>
  </div>
    <div class="col-7">
      <div class="card bg-light m-3 mb-2"">
        <div class="card-body">
          <h5 class="card-title">A bit more about the flat... 🏡</h5>
          <p class="card-text"><%= @flat.description %></p>
        </div>
      </div>
    </div>
    <div class="col-7">
      <div class="card bg-light m-3 mb-2"">
        <div class="card-body">
          <h5 class="card-title">Details</h5>
          <p class="card-text"><i class="fas fa-users"></i><%= @flat.number_of_guests %>
                  <i class="fas fa-euro-sign"></i><%= @flat.price_per_night %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/update.html.erb
<h1>Flats#update</h1>
<p>Find me in app/views/flats/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon p-3 mb-2 bg-light text-dark">
      <a class="navbar-brand" href="#">Simple Airbnb</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Add Flat", new_flat_path, class: "nav-link btn btn-outline-primary" %>
          </li>
        </ul>
      </div>
    </div>
    <%= yield %>
  </body>
</html>